name: Conjur Demo

# Watch Policy branch
on:
  push:
    branches:
      -  main

permissions:
  id-token: write
  contents: read

jobs:
  test-retrieve:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Retrieve Secrets
        env:
          CONJUR_URL: "https://asb-pov.secretsmgr.cyberark.cloud/api"
          CONJUR_ACCOUNT: "conjur"
          CONJUR_SERVICE_ID: "github-actions"
        run: |
          set -x
          CONJUR_URL="https://asb-pov.secretsmgr.cyberark.cloud/api"
          SECRET_ID="data%2Fvault%2Fasbdemo-azure-safe%2Fvm1%2Fpassword"
          CONJUR_SERVICE_ID="github-actions"
          CONJUR_ACCOUNT="conjur"
          echo "Retrieving JWT Token from Github"
          GIT_TOKEN=$(curl -s -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          echo "Authenticating to Conjur"
          SESSION_TOKEN=$(curl -s -X POST "$CONJUR_URL/authn-jwt/$CONJUR_SERVICE_ID/$CONJUR_ACCOUNT/authenticate" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept-Encoding: base64" --data-urlencode "jwt=$GIT_TOKEN")
          # Connect to the Conjur/Conjur REST API to retrieve secret value"
          SECRET_VALUE=$(curl -s --header "Authorization: Token token=\"$SESSION_TOKEN\"" "$CONJUR_URL/secrets/$CONJUR_ACCOUNT/variable/$SECRET_ID")
          echo " "
          echo "---- Retrieving Secret Value -----------"
          echo "ID: $SECRET_ID"
          echo "Value: $SECRET_VALUE"
          echo "----------------------------------------"
          echo " "
